### ISSUE TITLE
2014b+ compatibility

### ISSUE THREAD

**Issue by kristinbranson** [kristinbranson/cbtrack_GUI#4]
I get GUI errors when I use cbtrack on MATLAB 2014b. I'm guessing it is not compatible?

**Comment by jrglez** [comment]
I had the same problem the other day. Mi issue was with "textwrap". I think it does not work anymore with the new figure handles.

**Comment by kristinbranson** [comment]
It is weird! I think they changed the order of the arguments? If that is
the case, very annoying! I'm installing 2014a now.
