### ISSUE TITLE
specifying 'ignorebowls' in params.xml is broken

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/cbtrack_GUI#9]
In params.xml, set ignorebowls="3" (this attrib shows up under 'detect_rois' as well as 'track') and specify at least three ROIs via roimus and meanroiradius (I tested with precisely 3).

Now run things in a typical way and you get a harderror in Body Tracking setup (trace below).

It doesn't look like "ignorebowls" interacts with manual ROI specification (seems reasonable) or loading ROIs from a mat file (maybe someone would want to do this?), but not sure yet.

--- TRACE ---
Cell contents assignment to a non-cell array object.
Error in fit_to_ellipse_GUI (line 19)
        trx{j} = [];
Error in CountFliesPerROI_GUI (line 113)
        trx(:,i)=fit_to_ellipse_GUI(roidata,nflies_per_roi, dbkgd{i}, isfore{i},tracking_params);
Error in cbtrackGUI_tracker>pushbutton_accept_Callback (line 313)
            [count.nflies_per_roi,visdata.frames,visdata.framesW,visdata.dbkgdW,visdata.trxW] = ...

**Comment by allenleetc** [comment]
Is anybody using 'ignorebowls' in either ROI or tracking?

**Comment by arobie** [comment]
I think we just delete the ROIs at this point.
Shelby please correct if I'm wrong.
Alice

**Comment by allenleetc** [comment]
Similarly unchecking ROIs in the BodyTracker setup (setting "ignorebowls" at runtime) causes the same error.

**Comment by arobie** [comment]
I always just delete ROIs. I'm not sure I've ever noticed an 'ignorebowls'.

-Shelby
Sent from my iPhone

On Jun 26, 2015, at 4:35 PM, Alice Robie arobie@gmail.com wrote:

I think we just delete the ROIs at this point. 
Shelby please correct if I'm wrong. 
Alice 

On Fri, Jun 26, 2015 at 2:51 PM, allenleetc 
notifications@github.com wrote:

Is anybody using 'ignorebowls' in either ROI or tracking?

�
Reply to this email directly or 
view it on GitHub.

**Comment by allenleetc** [comment]
Harderror fixed. Handling of various ignore-ROI functionality investigated and detailed in CountFliesPerROI_GUI.m.
